<?php

namespace AppBundle\Repository;

/**
 * BacalaureatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacalaureatRepository extends \Doctrine\ORM\EntityRepository
{
}
