<?php

namespace AppBundle\Repository;

/**
 * CompanyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
