app_default:
    resource: "@AppBundle/Controller/DefaultController.php"
    prefix:    /
    type: annotation

app_stage:
    resource: "@AppBundle/Controller/StageController.php"
    prefix:    /stage
    type: annotation

app_company_type:
    resource: "@AppBundle/Controller/Company/CompanyTypeController.php"
    prefix:    /company/type
    type: annotation

app_company:
    resource: "@AppBundle/Controller/Company/CompanyController.php"
    prefix:    /company
    type: annotation

app_schooling_baccalaureat:
    resource: "@AppBundle/Controller/Schooling/BaccalaureatController.php"
    prefix:    /schooling/baccalaureat
    type: annotation

app_schooling_classroom:
    resource: "@AppBundle/Controller/Schooling/ClassRoomController.php"
    prefix:    /schooling/classroom
    type: annotation

app_schooling_promo:
    resource: "@AppBundle/Controller/Schooling/PromoController.php"
    prefix:    /schooling/promo
    type: annotation

app_schooling_student:
    resource: "@AppBundle/Controller/Schooling/StudentController.php"
    prefix:    /schooling/student
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"